before_build:
  - cmd: nuget restore HeaderArrayConverter\HeaderArrayConverter.sln

configuration: 
  - Release

image: 
  - Visual Studio 2017

platform: 
  - Any CPU

install:
  - ps: Install-Product node ''
  - npm install electron-builder@next
  - npm install HeaderArrayConverter\ViewHARX\package.json
