before_build:
  - cmd: nuget restore HeaderArrayConverter\HeaderArrayConverter.sln

configuration: 
  - Release

image: 
  - Visual Studio 2017

platform: 
  - Any CPU

install:
  - ps: Install-Product node ''
  - npm install -g npm
  - npm install HeaderArrayConverter\ViewHARX 

build:
  project: HeaderArrayConverter\HeaderArrayConverter

after_build:
  - cd .\HeaderArrayConverter\ViewHARX
  - node npm run dist-win
  
