before_build:
  - cmd: nuget restore HeaderArrayConverter\HeaderArrayConverter.sln

configuration: 
  - Release

image: 
  - Visual Studio 2017

platform: 
  - Any CPU

install:
  - ps: Install-Product node 6
  - npm install
